// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag at
// 2019-07-15 15:05:58.8115198 +0800 CST m=+0.645457401

package docs

import (
	"bytes"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "swagger": "2.0",
    "info": {
        "description": "东南大学成贤学院学生成绩录入及学生进行查询系统的标准API接口文档",
        "title": "成绩录入及查询系统标准接口文档",
        "termsOfService": "暂缺",
        "contact": {
            "name": "黄浩轩",
            "url": "https://github.com/huanghaoxuan",
            "email": "huanghaoxuan1998@outlook.com"
        },
        "license": {
            "name": "GNU GENERAL PUBLIC LICENSE Version 3, 29 June 2007",
            "url": "https://www.gnu.org/licenses/gpl-3.0.en.html"
        },
        "version": "0.0.1"
    },
    "host": "localhost:5201",
    "basePath": "/api",
    "paths": {
        "/course/delete/{id}": {
            "get": {
                "description": "删除一条课程信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "学籍信息"
                ],
                "summary": "删除一条课程信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "主键",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ]
            }
        },
        "/course/insert": {
            "post": {
                "description": "增加课程信息记录",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "课程信息"
                ],
                "summary": "增加课程信息记录",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "课程名",
                        "name": "name",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "学年",
                        "name": "year",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "学期",
                        "name": "semester",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"status\": 1}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/course/selectByPage": {
            "post": {
                "description": "分页查询课程信息记录",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "课程信息"
                ],
                "summary": "分页查询课程信息记录",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "查询页码",
                        "name": "pageNum",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "每页条数",
                        "name": "pageSize",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "课程名",
                        "name": "name",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "学年",
                        "name": "year",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "学期",
                        "name": "semester",
                        "in": "formData"
                    }
                ]
            }
        },
        "/course/update": {
            "post": {
                "description": "更新课程信息记录",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "课程信息"
                ],
                "summary": "更新课程信息记录",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "课程名",
                        "name": "name",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "学年",
                        "name": "year",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "学期",
                        "name": "semester",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"status\": 1}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/sourceStage/delete/{id}": {
            "get": {
                "description": "删除阶段性测验成绩",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "阶段性测验成绩"
                ],
                "summary": "删除阶段性测验成绩",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "主键",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ]
            }
        },
        "/sourceStage/insertStudent": {
            "post": {
                "description": "增加阶段性测验成绩",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "阶段性测验成绩"
                ],
                "summary": "增加阶段性测验成绩",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "学生名字",
                        "name": "name",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "学生学号",
                        "name": "studentId",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "教学班号",
                        "name": "teachingClassId",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "阶段性测验id",
                        "name": "sourceStageId",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "成绩注释",
                        "name": "scoresNote",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "成绩",
                        "name": "scores",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"status\": 1}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/sourceStage/selectByPage": {
            "post": {
                "description": "分页查询阶段性测验成绩",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "阶段性测验成绩"
                ],
                "summary": "分页查询阶段性测验成绩",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "查询页码",
                        "name": "pageNum",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "每页条数",
                        "name": "pageSize",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "学生名字",
                        "name": "name",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "学生学号",
                        "name": "studentId",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "教学班号",
                        "name": "teachingClassId",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "阶段性测验id",
                        "name": "sourceStageId",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "成绩注释",
                        "name": "scoresNote",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "成绩",
                        "name": "scores",
                        "in": "formData"
                    }
                ]
            }
        },
        "/sourceStage/updates": {
            "post": {
                "description": "批量更新阶段性测验成绩",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "阶段性测验成绩"
                ],
                "summary": "批量更新阶段性测验成绩",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "学生名字",
                        "name": "name",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "学生学号",
                        "name": "studentId",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "教学班号",
                        "name": "teachingClassId",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "阶段性测验id",
                        "name": "sourceStageId",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "成绩注释",
                        "name": "scoresNote",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "成绩",
                        "name": "scores",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"status\": 1}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/sourceStageInformation/delete/{id}": {
            "get": {
                "description": "删除阶段性测验信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "阶段性测验信息"
                ],
                "summary": "删除阶段性测验信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "主键",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ]
            }
        },
        "/sourceStageInformation/insert": {
            "post": {
                "description": "增加阶段性测验信息",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "阶段性测验信息"
                ],
                "summary": "增加阶段性测验信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "课程名字",
                        "name": "name",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "教学班号",
                        "name": "teachingClassId",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "阶段性测验序号",
                        "name": "scoresId",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "阶段性测验描述",
                        "name": "scoresNote",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"status\": 1}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/sourceStageInformation/selectByPage": {
            "post": {
                "description": "分页查询阶段性测验信息",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "阶段性测验信息"
                ],
                "summary": "查询阶段性测验信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "查询页码",
                        "name": "pageNum",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "每页条数",
                        "name": "pageSize",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "课程名字",
                        "name": "name",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "教学班号",
                        "name": "teachingClassId",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "阶段性测验序号",
                        "name": "scoresId",
                        "in": "formData"
                    }
                ]
            }
        },
        "/sourceStageInformation/update": {
            "post": {
                "description": "更新阶段性测验信息",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "阶段性测验信息"
                ],
                "summary": "更新阶段性测验信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "课程名字",
                        "name": "name",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "教学班号",
                        "name": "teachingClassId",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "阶段性测验序号",
                        "name": "scoresId",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "阶段性测验描述",
                        "name": "scoresNote",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"status\": 1}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/studentInformation/delete/{id}": {
            "get": {
                "description": "删除一条学生信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "学籍信息"
                ],
                "summary": "删除一条学生信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "主键",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ]
            }
        },
        "/studentInformation/insert": {
            "post": {
                "description": "增加学生信息记录",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "学籍信息"
                ],
                "summary": "增加学生信息记录",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "学生学号",
                        "name": "studentId",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "姓名",
                        "name": "name",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "原所在学院或部门",
                        "name": "departmentOld",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "原所在班级",
                        "name": "classOld",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "原所在年级",
                        "name": "gradeOld",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "现所在学院或部门",
                        "name": "departmentNew",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "现所在班级",
                        "name": "classNew",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "现所在年级",
                        "name": "gradeNew",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"status\": 1}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/studentInformation/selectByPage": {
            "post": {
                "description": "分页查询学生信息，如果查询第一页，返回总条数，条件非必需",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "学籍信息"
                ],
                "summary": "分页查询学生信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "查询页码",
                        "name": "pageNum",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "每页条数",
                        "name": "pageSize",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "学生学号",
                        "name": "studentId",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "姓名",
                        "name": "name",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "现所在学院或部门",
                        "name": "departmentNew",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "现所在班级",
                        "name": "classNew",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "现所在年级",
                        "name": "gradeNew",
                        "in": "formData"
                    }
                ]
            }
        },
        "/studentInformation/update": {
            "post": {
                "description": "更新学生信息记录",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "学籍信息"
                ],
                "summary": "更新学生信息记录",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "学生学号",
                        "name": "studentId",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "姓名",
                        "name": "name",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "原所在学院或部门",
                        "name": "departmentOld",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "原所在班级",
                        "name": "classOld",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "原所在年级",
                        "name": "gradeOld",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "现所在学院或部门",
                        "name": "departmentNew",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "现所在班级",
                        "name": "classNew",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "现所在年级",
                        "name": "gradeNew",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"status\": 1}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/studentInformation/upload": {
            "post": {
                "description": "上传学生信息表格文件，批量添加学生信息",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "学籍信息"
                ],
                "summary": "上传学生信息表格文件",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "文件",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"status\": 1}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/teacherInformation/delete/{id}": {
            "get": {
                "description": "删除一条老师信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "老师信息"
                ],
                "summary": "删除一条老师信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "主键",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ]
            }
        },
        "/teacherInformation/insert": {
            "post": {
                "description": "增加老师信息记录",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "老师信息"
                ],
                "summary": "增加老师信息记录",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "教师工号",
                        "name": "teacherId",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "姓名",
                        "name": "name",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "所在学院或部门",
                        "name": "department",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"status\": 1}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/teacherInformation/selectByPage": {
            "post": {
                "description": "分页查询老师信息，如果查询第一页，返回总条数，条件非必需",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "老师信息"
                ],
                "summary": "分页查询老师信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "查询页码",
                        "name": "pageNum",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "每页条数",
                        "name": "pageSize",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "教师工号",
                        "name": "teacherId",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "姓名",
                        "name": "name",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "所在学院或部门",
                        "name": "department",
                        "in": "formData"
                    }
                ]
            }
        },
        "/teacherInformation/update": {
            "post": {
                "description": "更新老师信息记录",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "老师信息"
                ],
                "summary": "更新老师信息记录",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "教师工号",
                        "name": "teacherId",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "姓名",
                        "name": "name",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "所在学院或部门",
                        "name": "department",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"status\": 1}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/teachingClass/delete/{id}": {
            "get": {
                "description": "删除一条教学班信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "教学班信息"
                ],
                "summary": "删除一条教学班信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "主键",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ]
            }
        },
        "/teachingClass/insert": {
            "post": {
                "description": "增加教学班信息记录",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "教学班信息"
                ],
                "summary": "增加教学班信息记录",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "学生学号",
                        "name": "studentId",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "姓名",
                        "name": "name",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "所在年级",
                        "name": "grade",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "所在学院或部门",
                        "name": "department",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "所在专业",
                        "name": "professional",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "所在班级",
                        "name": "class",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "课程名称",
                        "name": "courseName",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "课程id",
                        "name": "courseId",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "教学班号",
                        "name": "teachingClassId",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "任课老师名字",
                        "name": "courseTeacherName",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "任课老师id",
                        "name": "courseTeacherId",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"status\": 1}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/teachingClass/selectByPage": {
            "post": {
                "description": "分页查询教学班信息，如果查询第一页，返回总条数，条件非必需",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "教学班信息"
                ],
                "summary": "分页查询教学班信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "查询页码",
                        "name": "pageNum",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "每页条数",
                        "name": "pageSize",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "学生学号",
                        "name": "studentId",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "姓名",
                        "name": "name",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "所在年级",
                        "name": "grade",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "所在学院或部门",
                        "name": "department",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "所在专业",
                        "name": "professional",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "所在班级",
                        "name": "class",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "课程名称",
                        "name": "courseName",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "课程id",
                        "name": "courseId",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "教学班号",
                        "name": "teachingClassId",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "任课老师名字",
                        "name": "courseTeacherName",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "任课老师id",
                        "name": "courseTeacherId",
                        "in": "formData"
                    }
                ]
            }
        },
        "/teachingClass/update": {
            "post": {
                "description": "更新教学班信息记录",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "教学班信息"
                ],
                "summary": "更新教学班信息记录",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "学生学号",
                        "name": "studentId",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "姓名",
                        "name": "name",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "所在年级",
                        "name": "grade",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "所在学院或部门",
                        "name": "department",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "所在专业",
                        "name": "professional",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "所在班级",
                        "name": "class",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "课程名称",
                        "name": "courseName",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "课程id",
                        "name": "courseId",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "教学班号",
                        "name": "teachingClassId",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "任课老师名字",
                        "name": "courseTeacherName",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "任课老师id",
                        "name": "courseTeacherId",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"status\": 1}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/teachingClass/upload": {
            "post": {
                "description": "上传教学班表格文件，批量添加教学班信息",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "教学班信息"
                ],
                "summary": "上传教学班表格文件",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "文件",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"status\": 1}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/teachingClassInformation/delete/{id}": {
            "get": {
                "description": "删除一条教学班信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "教学班基本信息"
                ],
                "summary": "删除一条教学班信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "主键",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ]
            }
        },
        "/teachingClassInformation/insert": {
            "post": {
                "description": "增加教学班信息记录",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "教学班基本信息"
                ],
                "summary": "增加教学班信息记录",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "课程名称",
                        "name": "courseName",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "课程id",
                        "name": "courseId",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "教学班号",
                        "name": "teachingClassId",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "任课老师名字",
                        "name": "courseTeacherName",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "任课老师id",
                        "name": "courseTeacherId",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"status\": 1}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/teachingClassInformation/selectByPage": {
            "post": {
                "description": "分页查询教学班信息，如果查询第一页，返回总条数，条件非必需",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "教学班基本信息"
                ],
                "summary": "分页查询教学班信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "查询页码",
                        "name": "pageNum",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "每页条数",
                        "name": "pageSize",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "课程名称",
                        "name": "courseName",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "课程id",
                        "name": "courseId",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "教学班号",
                        "name": "teachingClassId",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "任课老师名字",
                        "name": "courseTeacherName",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "任课老师id",
                        "name": "courseTeacherId",
                        "in": "formData"
                    }
                ]
            }
        },
        "/teachingClassInformation/update": {
            "post": {
                "description": "更新教学班信息记录",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "教学班基本信息"
                ],
                "summary": "更新教学班信息记录",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "课程名称",
                        "name": "courseName",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "课程id",
                        "name": "courseId",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "教学班号",
                        "name": "teachingClassId",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "任课老师名字",
                        "name": "courseTeacherName",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "任课老师id",
                        "name": "courseTeacherId",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"status\": 1}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/user/login": {
            "post": {
                "description": "用于用户登录",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户"
                ],
                "summary": "登录",
                "parameters": [
                    {
                        "type": "string",
                        "description": "学生学号",
                        "name": "studentId",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "密码",
                        "name": "password",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "  \"token\": \"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1NjEyNjczNDIsImlhdCI6MTU2MTI2Mzc0MiwiaXNzIjoi5Lic5Y2X5aSn5a2m5oiQ6LSk5a2m6Zmi5oiQ57up5p-l6K-i57O757ufLS3pu4TmtanovakifQ.juqOf-lEq8bmWRBg1KHbmaqQK7vJMXJ-R5_tYrJAJs4",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/user/reset/{student_id}": {
            "get": {
                "description": "将密码重置为身份证后六位",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户"
                ],
                "summary": "重置密码",
                "parameters": [
                    {
                        "type": "string",
                        "description": "学生学号",
                        "name": "studentId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"status\": 1}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo swaggerInfo

type s struct{}

func (s *s) ReadDoc() string {
	t, err := template.New("swagger_info").Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, SwaggerInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
